"""fix_is_done_column

Revision ID: 6c1169433cb7
Revises: a258744595ca
Create Date: 2026-07-29 18:01:36.533750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1169433cb7'
down_revision: Union[str, None] = 'a258744595ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Dodajemy kolumnę z domyślną wartością '0' dla istniejących rekordów
    op.add_column(
        'tasks', 
        sa.Column('progress_prec', sa.Integer(), nullable=False, server_default='0')
    )
    
    # Usuwamy domyślną wartość na poziomie bazy, by nie wpływała na dalsze operacje
    op.alter_column('tasks', 'progress_prec', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'progress_prec')
    # ### end Alembic commands ###
