"""New column

Revision ID: 7feb62484b01
Revises: 1098012593cf
Create Date: 2026-08-13 17:49:00.469808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7feb62484b01'
down_revision: Union[str, None] = '1098012593cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'last_accessed_at')
    # ### end Alembic commands ###
