"""Add start_date and subtask fields

Revision ID: 8882ca29fd80
Revises: fa6316e52dce
Create Date: 2026-07-16 13:08:38.853483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8882ca29fd80'
down_revision: Union[str, Sequence[str], None] = 'fa6316e52dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_date')
    # ### end Alembic commands ###
