"""fix_is_done_column

Revision ID: a258744595ca
Revises: f6622ca55f06
Create Date: 2026-07-29 17:55:18.604896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a258744595ca'
down_revision: Union[str, None] = 'f6622ca55f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Dodajemy kolumnę z domyślną wartością (server_default='0')
    op.add_column(
        'tasks', 
        sa.Column('saved_progress', sa.Integer(), nullable=False, server_default='0')
    )
    
    # 2. Opcjonalnie: Usuwamy domyślną wartość serwera, jeśli nie chcesz, 
    # aby każda nowa kolumna miała domyślnie '0' na poziomie samej bazy SQL
    op.alter_column('tasks', 'saved_progress', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'progress_prec')
    op.drop_column('tasks', 'saved_progress')
    op.create_table('subtasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='subtasks_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subtasks_pkey')
    )
    op.create_index('ix_subtasks_id', 'subtasks', ['id'], unique=False)
    # ### end Alembic commands ###
