"""Update

Revision ID: d34559c5e95d
Revises: b36937bb96fe
Create Date: 2026-07-29 16:52:55.603425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34559c5e95d'
down_revision: Union[str, None] = 'b36937bb96fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_constraint('tasks_parent_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'saved_progress')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'progress_prec')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('progress_prec', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('saved_progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_parent_id_fkey', 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'is_completed')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    # ### end Alembic commands ###
