"""Pending changes

Revision ID: e34334e82f81
Revises: 947dd6836a90
Create Date: 2026-07-31 13:10:16.035546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34334e82f81'
down_revision: Union[str, None] = '947dd6836a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_changes_id'), 'pending_changes', ['id'], unique=False)
    op.create_index(op.f('ix_pending_changes_token'), 'pending_changes', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_changes_token'), table_name='pending_changes')
    op.drop_index(op.f('ix_pending_changes_id'), table_name='pending_changes')
    op.drop_table('pending_changes')
    # ### end Alembic commands ###
