"""create task_columns table

Revision ID: fa6316e52dce
Revises: 437a89aafc1f
Create Date: 2026-07-06 12:31:22.464357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa6316e52dce'
down_revision: Union[str, Sequence[str], None] = '437a89aafc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_columns_id'), 'task_columns', ['id'], unique=False)
    op.add_column('tasks', sa.Column('saved_progress', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('progress_prec', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('column_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_columns', ['column_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', postgresql.ENUM('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='taskstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'column_id')
    op.drop_column('tasks', 'progress_prec')
    op.drop_column('tasks', 'saved_progress')
    op.drop_index(op.f('ix_task_columns_id'), table_name='task_columns')
    op.drop_table('task_columns')
    # ### end Alembic commands ###
